name: API Client KMP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      enable_kotlin_daemon:
        description: 'Enable Kotlin/Native Daemon for build'
        type: boolean
        required: false
        default: false
      run_with_stacktrace:
        description: 'Run Gradle with --stacktrace'
        type: boolean
        required: false
        default: false
      run_with_info:
        description: 'Run Gradle with --info'
        type: boolean
        required: false
        default: false
      run_with_debug:
        description: 'Run Gradle with --debug'
        type: boolean
        required: false
        default: false

jobs:
  build-multiplatform:
    runs-on: macos-latest
    env:
      GRADLE_OPTS: "-Xmx4096M -Dorg.gradle.daemon.idletimeout=3600000"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build entire project
        run: ./gradlew build ${{ inputs.run_with_stacktrace && '--stacktrace' || '' }} ${{ inputs.run_with_info && '--info' || '' }} ${{ inputs.run_with_debug && '--debug' || '' }} ${{ inputs.enable_kotlin_daemon && '-Pkotlin.native.enableDaemon=true' || '' }}
