name: Release

on:
  push:
    branches:
      - main
      - staging
    paths:
      - '.github/workflows/**'
      - 'composeApp/**'
      - 'iosApp/**'
      - 'gradle/**'
      - 'modules/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'package.json'

  pull_request:
    branches:
      - main
      - staging
    paths:
      - '.github/workflows/**'
      - 'composeApp/**'
      - 'iosApp/**'
      - 'gradle/**'
      - 'modules/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'package.json'

#  workflow_dispatch:
#    inputs:
#      manual_release:
#        description: 'Manual trigger reason (e.g., Hotfix, Test)'
#        required: false
#        default: 'Manual release'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for semantic-release to analyze all commits

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Execute semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}# Built-in token provided by GitHub
        run: npx semantic-release
